runtime: python311

instance_class: B2

#service: backend-pichau-social-media

# env: flex
entrypoint: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT

runtime_config:
  operating_system: ubuntu22

basic_scaling:
  max_instances: 3
  idle_timeout: 15m
