"""auto-tables

Revision ID: 6476fb87437a
Revises: 1be0c6148221
Create Date: 2024-01-27 19:49:27.419314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6476fb87437a'
down_revision: Union[str, None] = '1be0c6148221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('installment', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('typeSocial', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_image'), 'images', ['image'], unique=False)
    op.create_index(op.f('ix_images_installment'), 'images', ['installment'], unique=False)
    op.create_index(op.f('ix_images_price'), 'images', ['price'], unique=False)
    op.create_index(op.f('ix_images_product_name'), 'images', ['product_name'], unique=False)
    op.create_index(op.f('ix_images_typeSocial'), 'images', ['typeSocial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_typeSocial'), table_name='images')
    op.drop_index(op.f('ix_images_product_name'), table_name='images')
    op.drop_index(op.f('ix_images_price'), table_name='images')
    op.drop_index(op.f('ix_images_installment'), table_name='images')
    op.drop_index(op.f('ix_images_image'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
